name: Auto Deploy to Capawesome

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Inject environment variables and generate environment.ts and Build Angular app
        env:
          MAPS_KEY: ${{ secrets.MAPS_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: npm run build

      - name: 🛠 Install Capawesome CLI
        run: npm install -g @capawesome/cli@latest

      - name: 🔐 Authenticate CLI
        run: npx capawesome login --token=ca_u9u23j3dmra0vwaze13nrk7brh3l47bo82xy2zb1dnl4kjqa

      - name: 🚀 Deploy Live Update to Capawesome
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          npx capawesome apps:bundles:create --appId=ca5644a6-9b83-4987-ae21-09060784ba34 --path=www --comment="Auto deploy: $COMMIT_SHA - $COMMIT_MSG"
